### ISSUE TITLE
Custom Character Set not used.

### ISSUE THREAD

**Issue by lakeykeith** [CodeDead/Advanced-PassGen#3]
**Describe the bug**
Doesn't use custom Character Set.

**To Reproduce**
1. Enter and save a Personalized Character Set. Suggest you removed 0Oo and iIl1 (all circles and verticals)
2. In both fields (See Screen Caps)
===Here is my Character Set===
ABCDEFGHJKPRTUVWXYZabcdefghjkpqrstuvwxyz~@#%^&*()_+23456789-={}\:";<>?/
======================
3. Make sure the "Allow Duplicates" Box is unchecked.
4. Save
5. Go to List tab and "Generate"

**Expected behavior**
Should have a list of 10 passwords that have:
1. no round characters, and 
2. no vertical characters
3. no duplicate characters within a password

**Screenshots**
![Settings A](https://user-images.githubusercontent.com/69764741/130292633-c6c7e981-8535-42a1-b4e6-3f8238788bff.PNG)
![No Round or verticals in CharacterSets 01](https://user-images.githubusercontent.com/69764741/130292664-56ac9e2c-d7d9-4abe-8551-f2cd25ce0cae.PNG)
![Output list has Round and verticals](https://user-images.githubusercontent.com/69764741/130292718-42abe948-0847-4cb2-bcbe-5a5ffb60a036.PNG)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19043.1165]
 - Advance PassGen Version: 1.7.0

**Additional context**
It is confusing that you would have **two different places to input custom Character Sets.**
1. Under Advanced Tab
2. Tools > Settings > General
(I put the same character set in both locations)

**Comment by CodeDead** [comment]
Hi @lakeykeith ,

This is indeed an ambiguous option. The character set in the settings menu can be different than the one being used in the main menu.

The character set in the settings menu is going to be the default character set that will be used if you do not edit any of the options in the main menu, but as you can see, changing options in the main menu will override that default character set.

Perhaps, the setting should simply be renamed to 'default character set' in the settings menu, or be removed altogether in the settings menu, in order to remove confusion about this option.

I would greatly appreciate your input regarding this UI decision.

**Comment by lakeykeith** [comment]
Yes the UI is confusing. But it doesn't appear to use much of the UI anyway.
I put **identical** custom character sets in both character set fields.
It didn't use (either of) them. It appears to be using default settings only.
Also, The "Allow duplicates" Box was not checked, yet the output has duplicates.

**Comment by CodeDead** [comment]
That's because the UI will add characters to the specified character set, depending on the options that you picked, but it does appear to be a bug if `Use advanced options` is checked and the advanced character set value is not being respected.

I will look into this. Thank you for reporting the issue.

**Comment by CodeDead** [comment]
This has been fixed in PR https://github.com/CodeDead/Advanced-PassGen/pull/5
